pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
				//sh 'mvn clean package' if pom.xml is available in root direcotry. In my app, inside devops java-tomcat-sample application is there
                sh 'mvn -f hello-world-tomcat-app-war/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/hello-world.war'
                }
            }
        }
         stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploying_Application_Staging_Enviornment'

            }
            
        }
       /*stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_Application_Prod_Env'
            }
        }
		*/
    }
}